services:
  redis:
    image: redis:latest
    container_name: babchuk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    container_name: babchuk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: babchuk
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build: .
    container_name: babchuk-server
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  redis_data:
  mysql_data: