spring:
  application:
    name: babchuk-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    urls-primary-name: "Babchuk Server API"
    enabled: true
    doc-expansion: list
    deep-linking: true
    show-common-extensions: true
    display-operation-id: false
    filter: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXP}
    refresh: ${JWT_REFRESH_EXP}